### ISSUE TITLE
  kotlin.TypeCastException: View LayoutParams must be of type 'SpanLayoutParams'

### ISSUE THREAD

**Issue by saefbadwan** [Arasthel/SpannedGridLayoutManager#13]
When i call this code from lets say a OnClickListener i get this error , but when from outer no error it seems that something to do with context.
-------------------------------------
FATAL EXCEPTION: main
                                                                                           Process: inducesmile.com.androidrecyclerviewgridview, PID: 4632
                                                                                           kotlin.TypeCastException: View LayoutParams must be of type 'SpanLayoutParams'
                                                                                               at com.arasthel.spannedgridlayoutmanager.SpannedGridLayoutManager.measureChild(SpannedGridLayoutManager.kt:209)
                                                                                               at com.arasthel.spannedgridlayoutmanager.SpannedGridLayoutManager.makeAndAddView(SpannedGridLayoutManager.kt:283)
                                                                                               at com.arasthel.spannedgridlayoutmanager.SpannedGridLayoutManager.fillAfter(SpannedGridLayoutManager.kt:615)
                                                                                               at com.arasthel.spannedgridlayoutmanager.SpannedGridLayoutManager.fillGap(SpannedGridLayoutManager.kt:576)
                                                                                               at com.arasthel.spannedgridlayoutmanager.SpannedGridLayoutManager.onLayoutChildren(SpannedGridLayoutManager.kt:182)
                                                                                               at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3719)
                                                                                               at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3436)
                                                                                               at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3988)
                                                                                               at android.view.View.layout(View.java:14817)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                               at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
                                                                                               at android.view.View.layout(View.java:14817)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                                               at android.view.View.layout(View.java:14817)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                               at android.view.View.layout(View.java:14817)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                                               at android.view.View.layout(View.java:14817)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                               at android.view.View.layout(View.java:14817)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                               at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                                               at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                                               at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                                               at android.view.View.layout(View.java:14817)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                               at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                                               at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                                               at android.view.View.layout(View.java:14817)
                                                                                               at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                                               at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1983)
                                                                                               at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1740)
                                                                                               at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
                                                                                               at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
                                                                                               at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                                               at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                                               at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                                               at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                                               at android.os.Handler.handleCallback(Handler.java:733)
                                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                               at android.os.Looper.loop(Looper.java:136)
                                                                                               at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                               at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                                               at dalvik.system.NativeStart.main(Native Method)

**Comment by saefbadwan** [comment]
Will ,, the problem is you need to set every view span if used this lib ,, if you put the code of setLayoutparams in on Click you did not sit adult span for each viewholder so you need to seit a defult SpanSize for each view

**Comment by abhinavmishra094** [comment]
i am also having same problem without problem without click listener where  do i have to set adult span

**Comment by mosamabinomar** [comment]
```
 if (position == 4) {
            holder.itemView.setLayoutParams(new SpanLayoutParams(new SpanSize(2, 2)));
        }else{
            holder.itemView.setLayoutParams(new SpanLayoutParams(new SpanSize(1,1)));
        }
```
**Do this in `onBindViewHolder`. For each itemview you have to set `layoutparams` to `spanlayoutparams`**
