### ISSUE TITLE
TypeCastException: Crashes the whole app, Untraceable

### ISSUE THREAD

**Issue by forntoh** [Arasthel/SpannedGridLayoutManager#33]
The library doesn't work for me, I don't know why, I get the following error
```java
kotlin.TypeCastException: View LayoutParams must be of type 'com.arasthel.spannedgridlayoutmanager.SpanLayoutParams'
        at com.arasthel.spannedgridlayoutmanager.SpannedGridLayoutManager.measureChild(SpannedGridLayoutManager.kt:213)
        at com.arasthel.spannedgridlayoutmanager.SpannedGridLayoutManager.makeAndAddView(SpannedGridLayoutManager.kt:287)
        at com.arasthel.spannedgridlayoutmanager.SpannedGridLayoutManager.fillAfter(SpannedGridLayoutManager.kt:595)
        at com.arasthel.spannedgridlayoutmanager.SpannedGridLayoutManager.fillGap(SpannedGridLayoutManager.kt:554)
        at com.arasthel.spannedgridlayoutmanager.SpannedGridLayoutManager.onLayoutChildren(SpannedGridLayoutManager.kt:184)
...
```

### TripsAdapter
```java
class TripsAdapter extends RecyclerView.Adapter<TripsAdapter.MyViewHolder> {

    @NonNull
    @Override
    public MyViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        return new MyViewHolder(LayoutInflater.from(parent.getContext()).inflate(R.layout.item_trip, parent, false));
    }

    @Override
    public void onBindViewHolder(@NonNull MyViewHolder holder, int position) {
        if (position == 0) holder.itemView.setLayoutParams(new SpanLayoutParams(new SpanSize(2, 2)));
    }

    @Override
    public int getItemCount() {
        return 9;
    }

    class MyViewHolder extends RecyclerView.ViewHolder {

        public MyViewHolder(View itemView) {
            super(itemView);
            ButterKnife.bind(this, itemView);
            itemView.setOnClickListener(this::onClick);
        }

        private void onClick(View view) {
            view.getContext().startActivity(new Intent(view.getContext(), LocalitiesActivity.class));
        }
    }
}
```
### HomeActivity
```java
public class HomeActivity extends BaseActivity {

    @BindView(R.id.rv_trips)
    RecyclerView rv_trips;
    private TripsAdapter tripsAdapter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_home);
        ButterKnife.bind(this);

        disableFlags(true);
        enableWhiteStatusBar();
        Objects.requireNonNull(getSupportActionBar()).setTitle("Trips");
        tripsAdapter = new TripsAdapter();
       
        SpannedGridLayoutManager spannedGridLayoutManager = new SpannedGridLayoutManager(SpannedGridLayoutManager.Orientation.VERTICAL, 3);
        spannedGridLayoutManager.setItemOrderIsStable(true);
        rv_trips.setLayoutManager(spannedGridLayoutManager);
        rv_trips.setAdapter(tripsAdapter);
    }

}
```

**Comment by Arasthel** [comment]
It's because you haven't set the SpanLayoutParams to every item, only to the first one.

**Comment by forntoh** [comment]
> It's because you haven't set the SpanLayoutParams to every item, only to the first one.

Okay Thanks, Let me try it.
